=== MoeMoeGit/app-manifests/schemas/manifest-v1.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Application manifest v1",
  "type": "object",
  "additionalProperties": false,
  "required": ["schema", "revision", "app", "updated_at", "devices"],
  "properties": {
    "schema": {
      "const": 1
    },
    "revision": {
      "type": "integer",
      "minimum": 1
    },
    "app": {
      "type": "string",
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "devices": {
      "type": "object",
      "propertyNames": {
        "pattern": "^[A-F0-9]{64}$"
      },
      "additionalProperties": {
        "type": "string",
        "format": "date"
      }
    }
  }
}

=== MoeMoeGit/app-manifests/apps/cckit/manifest-v1.json
{
  "schema": 1,
  "revision": 7,
  "app": "cckit",
  "updated_at": "2026-09-28T09:26:13+08:00",
  "devices": {
    "00FF269F390E9547AFD0A6EECFE28D38364B44FCE4EA084A45D01867FB0FA652": "2126-08-20",
    "387E4BD00F64F96EEA81191DEF247BA012E3459ED1228BFF29AB5A95EF5037EB": "2126-09-28",
    "4701110487A1D74C8976B7D6170A025AF636E7A2D04BA20D781395A51437F3F8": "2126-07-24",
    "4FE35B6040647003A94F36F7B49C103CC9E03CDF58DCB9A5D3671987EF9E30BA": "2126-09-28",
    "65009602A86A807BEC8B16230BB216292269D0D74B9432E15EBBFFD28A065D06": "2126-07-24",
    "7EE5B5E869C3CB0936F383F091AF1DE31245455BD454A53544E718001E2E66D7": "2126-07-24",
    "85114A91BE5CD43EB4E14CD1EE285F22DDC3CA35C614EF6C371E32F37EFEB01B": "2126-09-23",
    "9A2657327E40D337EAD8124640E10F954C39E0F334B1A3AD5D43583BBE11C6F8": "2126-07-24",
    "9FC8FE765CF6F85F57FC14EEA86BCD0EBB9487D23459F019B44166BC5B89F530": "2126-07-24",
    "AFE96CA5373A5BDE41D74E5CCBDF4ADC7D1C53842909C430542C865A917E6904": "2126-07-24",
    "B01663052ED9B42BF1412D7E629AA5A879933E4850BC70475A04F7619C37BE61": "2126-09-21",
    "B631A99468A0C722C1FC6C9F40D4601A5C5ACBE99A8D8CC22F1646B3766AAB5A": "2126-09-21",
    "C4019EC3A525A3B12F01466C674397D00747EA8B005C4F0D71E491C29A2AF383": "2126-07-13",
    "D11E079E245642615696FE06A5BB0C5E09779D049F72AC4ABCE64676C6614EF4": "2126-07-24",
    "D6024F725C808E21F78139DFF0B39A190426921C71AC6E4EE6E540217A6AAB28": "2126-07-24",
    "E40CADFADF24EAD8DE109BD6548311796B2ADCCAFCBD6F93D0C7231CB48653BD": "2126-07-24",
    "E948EB447477916D9AFB20085E08994D5EEAC3185954FE773FAE410C6AD31916": "2126-07-24",
    "EF0A7031D6CF75FE6EB494F545C2D655458C5DA9442A46BEA1123C3F1D3F4973": "2126-09-23",
    "F8615BAC77AFFB1EB0A3CCF6D061ED8170420C404C40E68D644E1D313C40AF13": "2126-07-24"
  }
}
